# Q2.
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms. for first 10 numbers, sum is == 44

def even_fib_sum(max_fib):
    i1 = 0
    i2 = 1
    sum = 0

    while True:
        fib = i1 + i2
        i1 = i2
        i2 = fib

        if fib > max_fib:
            break

        if fib % 2 == 0:
            sum += fib

    return sum


print(even_fib_sum(4000000))
